#!/bin/bash

# add vimrc to end of ~/.vimrc
cat ~/.dahlo-home/vimrc >> ~/.vimrc

echo "Added to .vimrc, please make sure vim-plug is installed,

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

Then run :PlugInstall in vim to install the missing plugins.

To install the color scheme run
mkdir ~/.vim/colors ; wget https://raw.githubusercontent.com/sickill/vim-monokai/master/colors/monokai.vim -O ~/.vim/colors/monokai.vim

"
